"""Build byte-inventoried examples from explicit CWL graphs and fixture contracts.

This is an authoring convenience, not an execution interpreter. Generated CWL
files are the process authority. --check compares every generated byte without
writing, including the current mock launcher's required identity.
"""
from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
VERSION = "0.1.0-draft.1"
PROFILE = f"urn:engineering-process-spec:core:{VERSION}"
IMPLEMENTATION = "urn:engineering-process-spec:mock-mcp"
APPLICATION = "urn:engineering-process-spec:mock-engineering"
SERVER = ROOT / "tests/providers/mock_mcp_server.py"
SNAPSHOTS = ROOT / "tests/providers/snapshots"


def encoded(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n").encode("utf-8")


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def quantity_input(name: str) -> dict:
    return {"type": {"type": "record", "name": name + "Quantity", "fields": [
        {"name": "value", "type": "double"},
        {"name": "unit", "type": "string"},
        {"name": "quantity", "type": "string"},
    ]}}


def step(key: str, source: str | list[str], expression: str) -> dict:
    arguments = {"source": source, "valueFrom": expression}
    if isinstance(source, list):
        arguments["linkMerge"] = "merge_nested"
    return {
        "run": "#mcp-call",
        "in": {
            "context": "epx_context",
            "node": {"default": "main/" + key},
            "binding": {"default": "engineering"},
            "tool": {"default": "engineering." + key},
            "arguments_json": arguments,
        },
        "out": ["result"],
    }


def workflow(count: int) -> dict:
    inputs = {"epx_context": "File", **{name: quantity_input(name) for name in ("length", "width", "thickness")}}
    steps = {
        "volume": step("volume", ["length", "width", "thickness"],
                       "$(JSON.stringify({length:self[0],width:self[1],thickness:self[2]}))"),
    }
    if count >= 2:
        inputs["density"] = quantity_input("density")
        steps["mass"] = step("mass", ["volume/result", "density"],
                             "$(JSON.stringify({volume:JSON.parse(self[0].contents).structuredContent,density:self[1]}))")
    if count >= 3:
        steps["record"] = step("record", "mass/result",
                               "$(JSON.stringify({measurement:JSON.parse(self.contents).structuredContent}))")
    tool_inputs = {
        name: {"type": "File" if name == "context" else "string",
               "inputBinding": {"prefix": "--" + name.replace("_", "-"), "position": position}}
        for position, name in enumerate(("context", "node", "binding", "tool", "arguments_json"), 1)
    }
    return {
        "cwlVersion": "v1.2",
        "$namespaces": {"epx": "urn:engineering-process-spec:profile:"},
        "$graph": [
            {"id": "#main", "class": "Workflow",
             "requirements": {
                 "epx:ExchangeRequirement": {"manifest": "requirements.json"},
                 "InlineJavascriptRequirement": {},
                 "StepInputExpressionRequirement": {},
                 "MultipleInputFeatureRequirement": {},
             },
             "inputs": inputs,
             "outputs": {key + "_result": {"type": "File", "outputSource": key + "/result"} for key in steps},
             "steps": steps},
            {"id": "#mcp-call", "class": "CommandLineTool", "baseCommand": "epx-mcp-call",
             "inputs": tool_inputs,
             "outputs": {"result": {"type": "File", "outputBinding": {"glob": "result.json", "loadContents": True}}}},
        ],
    }


def acceptance(key: str) -> dict:
    quantity = "volume" if key == "volume" else "mass"
    pointer = "/structuredContent" + ("/measurement" if key == "record" else "")
    return {
        "id": key + "-quantity", "node": "main/" + key,
        "valuePointer": pointer + "/value", "unitPointer": pointer + "/unit",
        "quantityPointer": pointer + "/quantity", "quantity": quantity,
        "unit": "m3" if quantity == "volume" else "kg",
        "expected": 0.00002 if quantity == "volume" else 0.157,
        "absoluteTolerance": 1e-12 if quantity == "volume" else 1e-6,
    }


def crate(name: str, payloads: dict[str, bytes]) -> bytes:
    return encoded({
        "@context": "https://w3id.org/ro/crate/1.2/context",
        "@graph": [
            {"@id": "ro-crate-metadata.json", "@type": "CreativeWork", "about": {"@id": "./"},
             "conformsTo": {"@id": "https://w3id.org/ro/crate/1.2"}},
            {"@id": "./", "@type": "Dataset", "name": name,
             "description": "Experimental fixed-call engineering process; mock provider, no CAD or material certification.",
             "datePublished": "2026-09-07",
             "license": "Licensing terms have not been selected; this metadata grants no additional permissions.",
             "mainEntity": {"@id": "workflow.cwl.json"}, "conformsTo": [{"@id": PROFILE}],
             "hasPart": [{"@id": path} for path in sorted(payloads)]},
            *[{"@id": path, "@type": "File", "sha256": digest(data), "contentSize": str(len(data))}
              for path, data in sorted(payloads.items())],
        ],
    })


def build_package(name: str, count: int, *, approval: bool = False, replacement: bool = False) -> dict[str, bytes]:
    keys = ("volume", "mass", "record")[:count]
    job = {key: {"value": value, "unit": "mm", "quantity": "length"}
           for key, value in (("length", 100), ("width", 80), ("thickness", 2.5))}
    if count >= 2:
        job["density"] = {"value": 7850, "unit": "kg/m3", "quantity": "density"}
    requirements = {
        "format": "epx-requirements", "version": VERSION, "profile": PROFILE,
        "process": {"id": "urn:engineering-process-spec:example:" + name, "revision": "1",
                    "entrypoint": "workflow.cwl.json#main"},
        "requiredFeatures": ["cwl-mcp-core", "quantity-acceptance", "resource-revisions"],
        "bindings": {"engineering": {
            "implementation": {"id": IMPLEMENTATION, "revision": VERSION, "artifactSha256": digest(SERVER.read_bytes())},
            "application": {"id": APPLICATION, "version": VERSION},
            "protocolVersion": "2025-11-25", "executionPlatforms": ["linux", "win32", "darwin"],
        }},
        "operations": {"main/" + key: {
            "binding": "engineering", "tool": "engineering." + key,
            "toolContract": "contracts/engineering." + key + ".tool.json",
            "effect": "mutation" if key == "record" else "read-only",
        } for key in keys},
        "resources": {"plate": {"binding": "engineering", "uri": "mock://plate", "revision": "r1"}},
        "job": "inputs/job.json", "acceptance": [acceptance(key) for key in keys],
        "extensions": {"urn:engineering-process-spec:example-notes": {
            "dataProvenance": "Synthetic test dimensions and density; no design or material certification.",
            "providerScope": "Explicitly named test-only mock MCP, never Solid Edge.",
        }},
    }
    if approval:
        requirements["requiredFeatures"].append("human-approval")
        requirements["extensions"]["urn:engineering-process-spec:approval-proposal"] = {
            "status": "preservation-only", "role": "quality-inspector",
            "subject": "Exact process revision and resulting measurement evidence; no decision supplied.",
            "approval": "not-granted", "scope": "Core executors must report unsupported before engineering calls.",
        }
    if replacement:
        requirements["process"]["id"] = "urn:engineering-process-spec:example:calculation"
        requirements["process"]["revision"] = "2"
        requirements["bindings"]["engineering"]["application"]["id"] = "urn:engineering-process-spec:mock-other-engineering"
        requirements["extensions"]["urn:engineering-process-spec:explicit-replacement"] = {
            "replacesProcessRevision": "1", "priorRequirements": "provenance/replaced-requirements.json",
            "priorApplication": APPLICATION,
            "replacementApplication": "urn:engineering-process-spec:mock-other-engineering",
            "affectedNodes": ["main/" + key for key in keys],
            "intent": "Explicitly authored test replacement; all affected acceptance must run again. Prior reports and approvals do not apply.",
        }
    expected = {
        "evidenceKind": "expected observations, not an execution report",
        "execution": "blocked" if approval else "succeeded",
        "acceptance": "not-run" if approval else "pass",
        "approval": "not-granted" if approval else "not-requested",
        "orderedNodes": ["main/" + key for key in keys],
        "structuredResults": {
            "main/volume": {"quantity": "volume", "value": 0.00002, "unit": "m3"},
            **({"main/mass": {"quantity": "mass", "value": 0.157, "unit": "kg"}} if count >= 2 else {}),
            **({"main/record": {"stored": True, "measurement": {"quantity": "mass", "value": 0.157, "unit": "kg"},
                                "resource": {"id": "mock://plate", "provider": APPLICATION, "revision": "r2"}}} if count >= 3 else {}),
        },
    }
    if approval:
        expected["structuredResults"] = {}
        expected["orderedNodes"] = []
        expected["diagnosticCategory"] = "unsupported"
    payloads = {"workflow.cwl.json": encoded(workflow(count)), "requirements.json": encoded(requirements),
                "inputs/job.json": encoded(job), "expected.json": encoded(expected)}
    if replacement:
        payloads["provenance/replaced-requirements.json"] = build_package("calculation", 2)["requirements.json"]
    for key in keys:
        payloads["contracts/engineering." + key + ".tool.json"] = (SNAPSHOTS / ("engineering." + key + ".tool.json")).read_bytes()
    payloads["ro-crate-metadata.json"] = crate(name, payloads)
    return payloads


def generated_files() -> dict[Path, bytes]:
    files: dict[Path, bytes] = {}
    for name, count in (("minimal", 1), ("calculation", 2), ("mock-handoff", 3), ("inspection-approval", 2), ("calculation-replacement", 2)):
        for path, content in build_package(name, count, approval=name == "inspection-approval", replacement=name == "calculation-replacement").items():
            files[ROOT / "examples" / name / path] = content
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated examples differ; never write")
    args = parser.parse_args()
    files = generated_files()
    stale = [path for path, content in files.items() if not path.is_file() or path.read_bytes() != content]
    if args.check:
        if stale:
            for path in stale:
                print("STALE " + path.relative_to(ROOT).as_posix(), file=sys.stderr)
            return 1
        print(f"Verified {len(files)} generated files and the mock launcher identity")
        return 0
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    print(f"Wrote {len(files)} generated files; run --check to verify reproducibility")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
